In [6]:
a = [1.0, 2.0, 1.0]

In [7]:
a[0]

1.0

In [8]:
a[2] = 3.0
a

[1.0, 2.0, 3.0]

In [9]:
import torch # <1>
a = torch.ones(3) # <2>
a

tensor([1., 1., 1.])

In [10]:
a[1]

tensor(1.)

In [11]:
float(a[1])

1.0

In [12]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [13]:
points = torch.zeros(6) # <1>
points[0] = 4.0 # <2>
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

In [14]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [15]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [16]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [17]:
points.shape

torch.Size([3, 2])

In [18]:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [19]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [20]:
points[0, 1]

tensor(1.)

In [21]:
points[0]

tensor([4., 1.])

In [80]:
some_list = list(range(6))
some_list[:]     # <1>
some_list[1:4]   # <2>
some_list[1:]    # <3>
some_list[:4]    # <4>
some_list[:-1]   # <5>
some_list[1:4:2] # <6>

[1, 3]

In [81]:
points[1:]       # <1>
points[1:, :]    # <2>
points[1:, 0]    # <3>
points[None]     # <4>

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [22]:
import torch
_ = torch.tensor([0.2126, 0.7152, 0.0722], names=['c'])

<ipython-input-22-32e0d8fb07c9>:2: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at ../c10/core/TensorImpl.h:1758.)
  _ = torch.tensor([0.2126, 0.7152, 0.0722], names=['c'])


In [23]:
img_t = torch.randn(3, 5, 5) # shape [channels, rows, columns]
weights = torch.tensor([0.2126, 0.7152, 0.0722])

In [24]:
img_t

tensor([[[ 0.4773,  0.7937,  0.3050, -0.0600,  0.6285],
         [-1.0500,  1.3660,  1.6224,  0.3825,  1.1289],
         [ 0.0771,  0.0700, -1.2769, -0.7485, -0.0310],
         [ 1.1936, -0.6076, -0.9341, -0.6366,  0.7457],
         [ 1.1266, -1.3096, -0.3198,  0.6434, -0.4177]],

        [[-0.1516, -1.3891,  0.0403, -1.2068, -1.8922],
         [-0.0126,  0.1978,  0.3586, -0.1843,  0.6288],
         [-0.1223,  0.8966, -0.1596,  0.4467,  0.2420],
         [-1.0818, -0.3521, -0.4948, -1.7009, -0.0371],
         [-0.0139,  1.5487,  0.5402,  0.7403,  0.8747]],

        [[-0.5482,  2.3727,  0.1610, -0.8129, -0.6408],
         [-0.4043,  0.5738, -0.5827,  1.6511,  0.2629],
         [-1.0324,  0.2788,  0.4995, -0.0666, -1.7229],
         [ 0.9676, -0.3995, -0.8790, -0.3492, -0.0700],
         [ 1.3381,  0.7773, -1.5187, -0.4593,  0.4516]]])

In [25]:
weights

tensor([0.2126, 0.7152, 0.0722])

In [26]:
batch_t = torch.randn(2, 3, 5, 5) # shape [batch, channels, rows, columns]

In [27]:
batch_t

tensor([[[[-0.0161,  0.8801,  0.4678, -0.3666, -0.4071],
          [ 1.7532, -0.1822, -1.3266,  0.4950,  1.2764],
          [-0.8123, -0.3940,  0.8326,  1.1390,  1.1458],
          [ 0.1082, -0.3881, -0.2889,  1.1062,  1.2420],
          [ 0.5990, -0.7543,  0.0439, -1.2164,  0.0976]],

         [[-0.2764, -1.6828,  1.3068, -0.6017, -0.1926],
          [-0.6802, -0.4244, -0.0306, -0.8466,  0.3421],
          [-0.7762,  1.1010, -0.2487,  2.2653, -0.4864],
          [ 1.9248,  1.0719,  0.8803, -0.7495,  0.2683],
          [ 0.1869,  0.6302, -1.3240, -0.0654,  0.6706]],

         [[ 0.1971, -1.6198, -1.6209,  1.2232, -1.0021],
          [-0.3530,  1.1843, -0.5948, -0.4661,  1.4808],
          [-1.7319,  0.7190,  0.0511, -0.0454,  0.5733],
          [ 0.5083,  0.2338,  0.1970, -0.1241, -0.9323],
          [ 2.1374, -0.1851, -0.3733, -1.3235,  0.7415]]],


        [[[ 0.2081,  0.9628,  0.7657,  1.2504,  1.5428],
          [ 0.1374,  0.4122,  1.0780, -0.7305, -0.5028],
          [-0.2907,  0.

In [28]:
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [29]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze(-1)
img_weights = (img_t * unsqueezed_weights)
batch_weights = (batch_t * unsqueezed_weights)
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [30]:
unsqueezed_weights.shape


torch.Size([3, 1, 1])

In [31]:
unsqueezed_weights

tensor([[[0.2126]],

        [[0.7152]],

        [[0.0722]]])

In [32]:
img_weights.shape

torch.Size([3, 5, 5])

In [33]:
img_t * unsqueezed_weights

tensor([[[ 0.1015,  0.1687,  0.0649, -0.0128,  0.1336],
         [-0.2232,  0.2904,  0.3449,  0.0813,  0.2400],
         [ 0.0164,  0.0149, -0.2715, -0.1591, -0.0066],
         [ 0.2538, -0.1292, -0.1986, -0.1353,  0.1585],
         [ 0.2395, -0.2784, -0.0680,  0.1368, -0.0888]],

        [[-0.1084, -0.9935,  0.0288, -0.8631, -1.3533],
         [-0.0090,  0.1415,  0.2565, -0.1318,  0.4497],
         [-0.0875,  0.6413, -0.1141,  0.3195,  0.1731],
         [-0.7737, -0.2518, -0.3539, -1.2165, -0.0265],
         [-0.0099,  1.1077,  0.3864,  0.5295,  0.6256]],

        [[-0.0396,  0.1713,  0.0116, -0.0587, -0.0463],
         [-0.0292,  0.0414, -0.0421,  0.1192,  0.0190],
         [-0.0745,  0.0201,  0.0361, -0.0048, -0.1244],
         [ 0.0699, -0.0288, -0.0635, -0.0252, -0.0051],
         [ 0.0966,  0.0561, -0.1096, -0.0332,  0.0326]]])

In [34]:
bbbb = torch.randn(1, 1)
bbbb

tensor([[0.7598]])

In [35]:
batch_t * bbbb

tensor([[[[-0.0122,  0.6687,  0.3555, -0.2785, -0.3093],
          [ 1.3322, -0.1384, -1.0080,  0.3761,  0.9699],
          [-0.6172, -0.2993,  0.6326,  0.8655,  0.8707],
          [ 0.0822, -0.2949, -0.2195,  0.8405,  0.9437],
          [ 0.4552, -0.5731,  0.0334, -0.9243,  0.0742]],

         [[-0.2101, -1.2787,  0.9930, -0.4572, -0.1464],
          [-0.5168, -0.3225, -0.0233, -0.6433,  0.2599],
          [-0.5898,  0.8366, -0.1889,  1.7213, -0.3696],
          [ 1.4625,  0.8145,  0.6689, -0.5695,  0.2039],
          [ 0.1420,  0.4788, -1.0060, -0.0497,  0.5095]],

         [[ 0.1497, -1.2308, -1.2316,  0.9294, -0.7615],
          [-0.2682,  0.8999, -0.4519, -0.3542,  1.1252],
          [-1.3160,  0.5463,  0.0388, -0.0345,  0.4356],
          [ 0.3862,  0.1777,  0.1497, -0.0943, -0.7084],
          [ 1.6241, -0.1406, -0.2837, -1.0057,  0.5634]]],


        [[[ 0.1581,  0.7316,  0.5818,  0.9501,  1.1723],
          [ 0.1044,  0.3132,  0.8191, -0.5551, -0.3820],
          [-0.2209,  0.

In [36]:
img_gray_weighted_fancy = torch.einsum('...chw,c->...hw', img_t, weights)
batch_gray_weighted_fancy = torch.einsum('...chw,c->...hw', batch_t, weights)
batch_gray_weighted_fancy.shape

torch.Size([2, 5, 5])

In [37]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])
weights_named

tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [38]:
img_named =  img_t.refine_names(..., 'channels', 'rows', 'columns')
batch_named = batch_t.refine_names(..., 'channels', 'rows', 'columns')
print("img named:", img_named.shape, img_named.names)
print("batch named:", batch_named.shape, batch_named.names)

img named: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch named: torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


In [39]:
weights_aligned = weights_named.align_as(img_named)
weights_aligned.shape, weights_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

In [40]:
gray_named = (img_named * weights_aligned).sum('channels')
gray_named.shape, gray_named.names

(torch.Size([5, 5]), ('rows', 'columns'))

In [41]:
try:
    gray_named = (img_named[..., :3] * weights_named).sum('channels')
except Exception as e:
    print(e)

Error when attempting to broadcast dims ['channels', 'rows', 'columns'] and dims ['channels']: dim 'columns' and dim 'channels' are at the same position from the right but do not match.


In [42]:
gray_plain = gray_named.rename(None)
gray_plain.shape, gray_plain.names

(torch.Size([5, 5]), (None, None))

In [73]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

In [74]:
short_points.dtype

torch.int16

In [75]:
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()

In [76]:
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)

In [77]:
double_points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)

In [78]:
points_64 = torch.rand(5, dtype=torch.double)  # <1>
points_short = points_64.to(torch.short)
points_64 * points_short  # works from PyTorch 1.3 onwards

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

In [93]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [94]:
a = torch.ones(3, 2)
a_t = a.transpose(0, 1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [43]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [44]:
points_storage = points.storage()
points_storage[0]

4.0

In [45]:
points.storage()[1]

1.0

In [95]:
a = torch.ones(3, 2)

In [96]:
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [46]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_storage = points.storage()
points_storage[0] = 2.0
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

In [47]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point.storage_offset()

2

In [48]:
second_point.size()

torch.Size([2])

In [49]:
second_point.shape

torch.Size([2])

In [50]:
points.stride()

(2, 1)

In [51]:
second_point = points[1]
second_point.size()

torch.Size([2])

In [52]:
second_point.storage_offset()

2

In [53]:
second_point.stride()

(1,)

In [54]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point[0] = 10.0
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [55]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [56]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [57]:
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [58]:
id(points.storage()) == id(points_t.storage())

True

In [59]:
points.stride()

(2, 1)

In [60]:
points_t.stride()

(1, 2)

In [61]:
some_t = torch.ones(3, 4, 5)
transpose_t = some_t.transpose(0, 2)
some_t.shape

torch.Size([3, 4, 5])

In [62]:
transpose_t.shape

torch.Size([5, 4, 3])

In [63]:
some_t.stride()

(20, 5, 1)

In [64]:
transpose_t.stride()

(1, 5, 20)

In [65]:
points.is_contiguous()

True

In [66]:
points_t.is_contiguous()

False

In [67]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [68]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [69]:
points_t.stride()

(1, 2)

In [70]:
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [71]:
points_t_cont.stride()

(3, 1)

In [72]:
points_t_cont.storage()

 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [79]:
# reset points back to original value
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [86]:
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')

In [87]:
points_gpu = points.to(device='cuda')

In [88]:
points_gpu = points.to(device='cuda:0')

In [89]:
points = 2 * points  # <1>
points_gpu = 2 * points.to(device='cuda')  # <2>

In [90]:
points_gpu = points_gpu + 4

In [91]:
points_cpu = points_gpu.to(device='cpu')

In [92]:
points_gpu = points.cuda()  # <1>
points_gpu = points.cuda(0)
points_cpu = points_gpu.cpu()

In [82]:
points = torch.ones(3, 4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [83]:
points = torch.from_numpy(points_np)

In [84]:
torch.save(points, '../data/p1ch3/ourpoints.t')

RuntimeError: ignored

In [ ]:
with open('../data/p1ch3/ourpoints.t','wb') as f:
   torch.save(points, f)

In [ ]:
points = torch.load('../data/p1ch3/ourpoints.t')

In [ ]:
with open('../data/p1ch3/ourpoints.t','rb') as f:
   points = torch.load(f)

In [ ]:
import h5py

f = h5py.File('../data/p1ch3/ourpoints.hdf5', 'w')
dset = f.create_dataset('coords', data=points.numpy())
f.close()

In [ ]:
f = h5py.File('../data/p1ch3/ourpoints.hdf5', 'r')
dset = f['coords']
last_points = dset[-2:]

In [ ]:
last_points = torch.from_numpy(dset[-2:])
f.close()

In [85]:
!nvcc -V
import torch

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_Mar__8_18:18:20_PST_2022
Cuda compilation tools, release 11.6, V11.6.124
Build cuda_11.6.r11.6/compiler.31057947_0


### [1] list(range(9))からテンソルaを作成して、サイズ、オフセット、ストライドを確認してください。
※ ここではGoogle Colaraboratoryでの実行を想定しています。

####（a） b = a.view(3, 3)を使って新しいテンソルを作成します。viewはどんな動作をするのか？またaとbが同じストレージを共有していることを確認してください。

In [103]:
import numpy as np
import torch 

a = torch.arange(0,9)
b = a.view(3,3)

id(a.storage()) == id(b.storage())

True

In [104]:
print(a)
print(b)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [105]:
# このように、変数aとbは同じストレージの値を参照していますが、テンソルの形が異なっており、この形の変形はa.view(3.3)で実行されています

#### （b） テンソル c = b[1:,1:]を作成し、サイズ、オフセット、ストライドを確認してください

In [106]:
c = b[1:,1:]
print(f"size: {c.size()}\n", f"offset: {c.storage_offset()}\n", f"stride: {c.stride()}\n")

size: torch.Size([2, 2])
 offset: 4
 stride: (3, 1)



### [2] torch ライブラリからcosineやsquare rootのような数学の演算に対応する関数を見つけてください。

In [107]:
# これはエラー：float型にする
print(torch.cos(a))

tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])


In [108]:
# aがLong型である点が問題です

In [109]:
# float型にする
print(torch.cos(a.float()))

tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])
